### ISSUE TITLE
redmi ax3000 ra81  Programmer flash firmware 5F1GQ5REYIG

### ISSUE THREAD

**Issue by fancire** [shell-script/unlock-redmi-ax3000#11]
Hello, do you have firmware for the flash memory of Redmi ax3000 ra81 router? I used a programmer to clear the data of the flash memory chip, which caused the failure, which caused it to fail to start normally. The flash memory chip model is 5F1GQ5REYIG.

**Comment by 1715173329** [comment]
Unfortunately no. Try to search it on right.com.cn
