### ISSUE TITLE
固化ssh时WiFi丢失

### ISSUE THREAD

**Issue by xxvinciaxx** [shell-script/unlock-redmi-ax3000#2]
尝试固化ssh时WiFi丢失，WiFi名称显示undefined
尝试恢复出厂，恢复官方固件，以及官方救砖工具都无法恢复

**Comment by 1715173329** [comment]
把之前备份的 `bdata_mtd9.img` 刷入到 mtd9 试试。

**Comment by 1715173329** [comment]
Closed due to stale.
