### ISSUE TITLE
ax3000 ra81型号 无法降级

### ISSUE THREAD

**Issue by stevelannist** [shell-script/unlock-redmi-ax3000#5]

**Comment by 1715173329** [comment]
?

**Comment by stevelannist** [comment]
刚刚网掉了不好意思 不知道有没有ra81型号的降级固件呢

**Comment by 1715173329** [comment]
这个仓库是给 ax6 的，原本按照规格就应该叫 ax3000，没想到小米出了个阉割版的真 ax3000。
目前没有收集过 ax3000 相关信息，过于垃圾，建议退货。

**Comment by stevelannist** [comment]
好的 谢谢 可惜 半价买的也不值吗

**Comment by 1715173329** [comment]
半价。。只能说当个 ap 吧，关键这玩意儿当 ap 也不老实。等看看有没有谁有兴趣破解一下 ssh 干掉里面的数据收集服务吧。

**Comment by dexin-peng** [comment]
同问

**Comment by theonedemon** [comment]
up?

**Comment by theonedemon** [comment]
a have some device, and wish open ssh, any news people?
