### ISSUE TITLE
ax3000 1.0.15 build

### ISSUE THREAD

**Issue by mitchell931993** [shell-script/unlock-redmi-ax3000#9]
Is this still valid for xiaomi ax3000?
I was on the 1.0.17 firmware but downgraded to 1.0.15 thinking it was a smart move. I seem to be able to get the token return from the other open wrt, but still no luck. 
I also am not having any luck with https://github.com/acecilia/OpenWRTInvasion. 
Do you have a bin download of the 1.0.17 version?

**Comment by 1715173329** [comment]
No, I'm not interested in Xiaomi's crappy fw so have no other versions.

1.0.18 I uploaded should work fine, what do you mean by "no luck"? btw this is for `ra69`, not `ra80` or `ra81`.
